### ISSUE TITLE
矿大21级校友前来贺电

### ISSUE THREAD

**Issue by ramsayi** [Haorical/haorical.github.io#1]
矿大21级遥感校友前来贺电😂互换友联走一波不？

**Comment by ramsayi** [comment]
ramsayi.cn

**Comment by Haorical** [comment]
@ramsayi  我那博客hexo搭建的，好像没友链功能，我先研究研究

**Comment by ramsayi** [comment]
@Haorical 大佬牛啊，已经搞好了🤣

**Comment by Haorical** [comment]
@ramsayi  应该是没问题了 这个是我的 

名称：haorical

主页链接：https://haorical.xyz

头像链接：https://haorical.xyz/images/avatar.jpg

说明信息：一分耕耘，一分收获

**Comment by ramsayi** [comment]
@Haorical 
名称：Ramsayi
主页链接：https://ramsayi.cn
头像链接：https://i.loli.net/2021/08/29/y9prTaRZugj8QBb.jpg
说明信息：满堂花醉三千客，一剑霜寒十四州。

**Comment by ramsayi** [comment]
这个样子
![](https://i.loli.net/2021/09/23/SyfcWxJZD38sbUE.png)

**Comment by Haorical** [comment]
@ramsayi 哦哦可以，我这个应该就是默认的next的图标

**Comment by ramsayi** [comment]
弄好了！👌
![](https://i.loli.net/2021/09/23/5nv1skywUI2qOdi.png)
